finish 05/01
js-tasks-ru/nodejs-20201126-2_honcharenko-zhenya pull request #4
Opened 2020-12-09 09:08 UTC by HoncharenkoZhenya

2020-12-09 09:42 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Файловый сервер - отдача файла
+ файл отдается по запросу
+ если файла нет - отдается 404
- если файла нет - отдается 404
```

2020-12-09 11:49 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Файловый сервер - отдача файла
+ файл отдается по запросу
+ если файла нет - отдается 404
+ если путь вложенный - возвращается ошибка 400
```

Добавляю преподавателя (@RidgeA) для код-ревью, посмотрим что он скажет :)

2020-12-09 20:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @RidgeA

2020-12-09 21:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @RidgeA

2020-12-09 22:07 UTC, RidgeA requested changes

2020-12-09 22:07 UTC, RidgeA commented on 05-http-server-streams/01-file-server-get/server.js
> +      readStream.on('readable', () => {
Использование события `readable` это достаточно низкоуровневый способ работы со стримом. 
Для большинства задач достаточно события `data` или `pipe`.
Эта задача не требует какого-то взаимодействия с передаваемыми данными, потому использование `pipe` будет тут предпочтительнее. 

Попробуйте переделать задачу используя `pipe` метод стрима.

2020-12-09 22:07 UTC, RidgeA commented on 05-http-server-streams/02-file-server-post/server.js
> +      const limitStream = new LimitSizeStream({limit: 2 ** 20, encoding: 'utf-8'});
В данном случае указание кодировки будет не совсем правильным, поскольку мы не знаем что за файл к нам приходит. Это может быть текст, а может быть и изображение или видео. 
И `LimitSizeStream` должен считать именно количество байт, а не символов, в случае использования кодировки `utf-8` 1 символ далеко не всегда 1 байт

2020-12-09 22:07 UTC, RidgeA commented on 05-http-server-streams/02-file-server-post/server.js
> +      limitStream.on('data', onData);
Как и в предыдущем задании использование `pipe` тут будет предпочтительнее. 
Попробуйте переделать используя метод `pipe`.

2020-12-10 08:19 UTC, HoncharenkoZhenya commented on 05-http-server-streams/01-file-server-get/server.js
> +      readStream.on('readable', () => {
Переделал

2020-12-10 08:19 UTC, HoncharenkoZhenya commented on 05-http-server-streams/02-file-server-post/server.js
> +      const limitStream = new LimitSizeStream({limit: 2 ** 20, encoding: 'utf-8'});
Убрал кодировку

2020-12-10 08:19 UTC, HoncharenkoZhenya commented on 05-http-server-streams/02-file-server-post/server.js
> +      limitStream.on('data', onData);
Переделал

2020-12-10 08:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @RidgeA

2020-12-10 09:01 UTC, RidgeA approved these changes

2020-12-10 09:01 UTC, RidgeA commented on 05-http-server-streams/02-file-server-post/server.js
> +      req.on('data', (chunk) => {
Самостоятельно писать в стрим не нужно вызов `pipe` можно выстраивать в цепочку
`source.pipe(transform).pipe(destination)`

В данном случае это будет req.pipe(limitStream).pipe(writeStream);

В таком случае достаочно подписаться на ошибки и событие окончания стрима.

Да, кстати, `isFileCreated` можно заменить [writable.writableFinished](https://nodejs.org/dist/latest-v15.x/docs/api/stream.html#stream_writable_writablefinished) тем более, что изменение этого флага в обработчике события `end` LimitSizeStream не гарантирует, что данные были полностью обработаны `writableStream`


После того, как задача будет принята - посмотрите предлагаемое решение

2020-12-10 09:02 UTC, merged